apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: add-techdocs-to-repo
  title: Add Tech docs to existing repo template
  description: scaffolder v1beta3 template to push techdocs starter template to existing github repo
spec:
  owner: user:default/apeksh.agarwal
  type: service

  parameters:
    - title: Fill in some steps
      required:
        - component_name
        - title
        - sourceBranchName
        - targetBranchName
      properties:
        component_name:
          title: Name of component
          type: string
          description: Choose the name of entity to add techdocs for
          ui:field: EntityPicker
          ui:options:
            allowedKinds:
              - Component
              - API
              - System
              - Domain
              - Resource
        title:
          title: Title
          type: string
          description: Title of documentation
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Description of the documentation
        sourceBranchName:
          title: Source branch name
          type: string
          description: Enter name for source branch to create a merge request from
          ui:field: EntityNamePicker
        targetBranchName:
          title: Target branch name
          type: string
          description: Enter name of existing branch to merge with
          ui:field: EntityNamePicker

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - Backstage-Testing-Org
    
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          title: ${{parameters.title}}
          description: ${{ parameters.description }}
          component_name: ${{ parameters.component_name }}


    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Add techdocs starter template: ${{parameters.title}}"
        branchName: add-techdocs-${{parameters.sourceBranchName}}
        targetBranchName: ${{ parameters.targetBranchName }}
        description: |
          # : ${{parameters.title}}

          ${{ parameters.description if parameters.description }}
      
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: 'To reference techdocs, add annotation `backstage.io/techdocs-ref: dir:.` in catalog.yaml'


  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        title: "Go to PR"
